local M = {}

M.base_30 = {
  white = "#dfdfe0",
  black = "#242424",
  darker_black = "#1d1d1d",
  black2 = "#242424",
  one_bg = "#2b2b2b",
  one_bg2 = "#323232",
  one_bg3 = "#404040",
  grey = "#4e4e4e",
  grey_fg = "#5c5c5c",
  grey_fg2 = "#636363",
  light_grey = "#737373",
  red = "#ee4d4d",
  baby_pink = "#FF7EB6",
  pink = "#FF7EB6",
  line = "#2a2a2a",
  green = "#b4cda7",
  vibrant_green = "#b4cda7",
  nord_blue = "#78A9FF",
  blue = "#78A9FF",
  yellow = "#dbdba9",
  sun = "#ffe731",
  purple = "#BE95FF",
  dark_purple = "#9B69D9",
  teal = "#33B1FF",
  orange = "#cd9077",
  cyan = "#4fc8af",
  statusline_bg = "#1d1d1d",
  lightbg = "#2b2b2b",
  pmenu_bg = "#dfdfe0",
  folder_bg = "#78A9FF",
}

M.base_16 = {
  base00 = "#202020",
  base01 = "#282828",
  base02 = "#262728",
  base03 = "#363738",
  base04 = "#525253",
  base05 = "#f2f4f8",
  base06 = "#e0e0e0",
  base07 = "#ffffff",
  base08 = "#78A9FF",
  base09 = "#08BDBA",
  base0A = "#3DDBD9",
  base0B = "#25be6a",
  base0C = "#33B1FF",
  base0D = "#c485bf",
  base0E = "#BE95FF",
  base0F = "#9bdbfe",
}

M.polish_hl = {
  treesitter = {
    ["@text"] = { fg = M.base_30.white },
    ["@text.emphasis"] = { fg = M.base_30.white, italic = true },
    ["@text.strong"] = { fg = M.base_30.white, bold = true },
    ["@text.underline"] = { fg = M.base_30.white, underline = true },
    ["@text.strike"] = { fg = M.base_30.white, strikethrough = true },

    ["@lsp.type.decorator"] = { fg = M.base_16.base0D },
    ["@keyword.return"] = { fg = M.base_16.base0D },
    ["@function"] = { fg = M.base_30.yellow },
    ["@keyword.function"] = { fg = M.base_30.yellow },
    ["@function.method"] = { fg = M.base_30.yellow },
    ["@function.macro"] = { fg = M.base_30.yellow },
    ["@constant.macro"] = { fg = M.base_30.blue },
    ["@constant.builtin"] = { fg = M.base_30.blue },
    ["@constant"] = { fg = M.base_30.blue },
    ["@type.builtin"] = { fg = M.base_30.blue },
    ["@module"] = { fg = M.base_30.cyan },
    ["@operator"] = { fg = M.base_30.white },
    ["String"] = { fg = M.base_30.orange },
    ["@string"] = { fg = M.base_30.orange },
    ["@string.escape"] = { fg = M.base_30.orange },
    ["@string.special"] = { fg = M.base_30.orange },
    ["@string.regex"] = { fg = M.base_30.orange },
    ["@string.regexp"] = { fg = M.base_30.orange },
    ["@string.special.url"] = { fg = M.base_30.orange },
    ["@lsp.type.string"] = { fg = M.base_30.orange },
    ["@number"] = { fg = M.base_30.vibrant_green },
    ["@ponctuation.delimiter"] = { fg = M.base_30.white },
    ["@punctuation.bracket"] = { fg = M.base_30.white },
    ["@parenthesis"] = { fg = M.base_30.white },
    ["@punctuation.special"] = { fg = M.base_30.white },
    ["@keyword"] = { fg = M.base_16.base0D },
    ["@keyword.conditional"] = { fg = M.base_16.base0D },
    ["@keyword.directive"] = { fg = M.base_16.base0D },
    ["@keyword.directive.define"] = { fg = M.base_16.base0D },
    ["@constructor"] = { fg = M.base_16.base0D },
    ["@lsp.event"] = { fg = M.base_16.base0D },
    ["@lsp.type.class"] = { fg = M.base_30.cyan },
    ["@lsp.type.struct"] = { fg = M.base_30.cyan },
    ["@lsp.type.enum"] = { fg = M.base_30.cyan },
    ["@variable"] = { fg = M.base_16.base0F },
    ["@variable.member"] = { fg = M.base_16.base0F },
    ["@variable.member.key"] = { fg = M.base_16.base0F },
    ["@variable.parameter"] = { fg = M.base_16.base0F },
    ["@lsp.type.property"] = { fg = M.base_16.base0F },
    ['RainbowDelimiterYellow'] = { fg = M.base_30.sun },
    ['RainbowDelimiterViolet'] = { fg = M.base_16.base0D },
    ['RainbowDelimiterBlue'] = { fg = M.base_30.blue },
    ['LineNr'] = { fg = M.base_30.light_grey },
    ['Visual'] = { bg = M.base_16.base03 },
    ['CursorLineNr'] = { fg = M.base_30.white, bold = true },
    ['CursorLine'] = { bg = M.base_16.base02, blend = 50 },
    ['NvimTreeLine'] = { bg = M.base_16.base03 },
    ['ScrollBarHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarCursor'] = { bg = M.base_16.base03 },
    ['ScrollBarCursorHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarSearchHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarErrorHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarWarnHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarInfoHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarHintHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarMiscHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarGitAddHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarGitChangeHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarGitDeleteHandle'] = { bg = M.base_16.base03 },
    ['ScrollBarGitConflictHandle'] = { bg = M.base_16.base03 },

  },
}

M.type = "dark"

M = require("base46").override_theme(M, "vscode")

return M
